apiVersion : app/v1
kind : Deployment
metadata:
  name: auth
  labels:
    app: auth 

spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth
    strategry:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 3
    template:
      metadata:
        labels:
          app: auth
      spec:
        containers:
        - name: auth
          image: abdullamoosa28/auth
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
              name: auth-configmap
            - secretRef:
              name: auth-secret