apiVersion: v1
kind: Service
metadata: 
  name: rabbitmq
spec:
  type: ClusterIP
  selector:
    app: rabbitmq
# One port for graphical UI and another for sending messages to queue.
# We need to access the http port from outside the cluster. So, it is necessary to create an ingress for accessing this port
  ports:
    - name: http
      protocol: TCP
      port: 15672
      targetPort: 15672 
    - name: ampq
      protocol: TCP
      port: 5672
      targetPort: 5672